#!/bin/sh

export PATH=$PATH:/usr/local/bin
export NODE_PATH=$NODE_PATH:/usr/local/lib/node_modules
export PORT=80
export SERVER_IFACE='0.0.0.0'

case "$1" in
  start)
  exec forever --sourceDir=/var/app --workingDir=/var/app -p /var/run/forever start bin/www
  ;;

  stop)
  exec forever stop --sourceDir=/var/app bin/www
  ;;
esac

exit 0